import Image from "next/image"
import im from "../../public/image.jpg"


/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HC0xfkmVCb6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function About() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container grid gap-10 px-4 md:px-6 lg:grid-cols-2 lg:gap-20">
        <div className="order-2 lg:order-1">
          <Image
            alt="image"
            className="mx-auto rounded-xl object-cover"
            height={600}
            src={im}
            style={{
              aspectRatio: "500/600",
              objectFit: "cover",
            }}
            width={500}
          />
        </div>
        <div className="order-1 lg:order-2 space-y-6">
          <div className="space-y-4">
            <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">About the Creator</h1>
            <p className="max-w-[600px] text-gray-500 md:text-xl dark:text-gray-400">
              Deepanshu is the creator of this site, dedicated to sharing his knowledge and insights on a variety of topics.
              With a passion for writing and a deep understanding of his subject matter, John strives to provide his
              readers with engaging and informative content.
            </p>
          </div>
          <div className="grid grid-cols-2 gap-6">
            <div className="space-y-2">
              <PenIcon className="h-5 w-5 text-gray-900 dark:text-gray-50" />
              <h3 className="text-lg font-medium">Experienced Developer</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Deepanshu has been developing apps and site  professionally for over 2 years, honing his craft and developing a unique product.
              </p>
            </div>
            <div className="space-y-2">
              <BookOpenIcon className="h-5 w-5 text-gray-900 dark:text-gray-50" />

              <h3 className="text-lg font-medium">Avid Researcher</h3>
              <p className="text-gray-500 dark:text-gray-400">
                Deepanshu is constantly researching and exploring new topics to provide his users with the most up-to-date
                and accurate Product.
              </p>
            </div>
            <div className="space-y-2">
              <UsersIcon className="h-5 w-5 text-gray-900 dark:text-gray-50" />
              <h3 className="text-lg font-medium">Community Focused</h3>
              <p className="text-gray-500 dark:text-gray-400">
                John values his readers and is dedicated to fostering a supportive and engaged community around his
                blog.
              </p>
            </div>
            <div className="space-y-2">
              <LightbulbIcon className="h-5 w-5 text-gray-900 dark:text-gray-50" />
              <h3 className="text-lg font-medium">Innovative Thinker</h3>
              <p className="text-gray-500 dark:text-gray-400">
                John is always looking for new and creative ways to present information and engage his audience.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}

function BookOpenIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  )
}


function LightbulbIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>
  )
}


function PenIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
    </svg>
  )
}


function UsersIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
