"use client";

import axios from "axios";
import { useRouter } from "next/navigation";
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yb0qaJBZOkE
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { useState } from "react"

/** Add fonts into your Next.js project:

import { Oswald } from 'next/font/google'
import { Bricolage_Grotesque } from 'next/font/google'

oswald({
  subsets: ['latin'],
  display: 'swap',
})

bricolage_grotesque({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function CreateBlog() {

  const [title,setTitle] = useState('');
  const [content,setContent] = useState('');
  const [image,setImage] = useState('');
  const [error,setError] = useState('');
  const [loading,setLoading] = useState(false);

  const router = useRouter();

  const handlePost = async(e:any)=>{
    try{
      e.preventDefault();
      setLoading(true);
      const res = await axios.post("/api/blogs",{title,content,image});
      console.log(res.data);
      router.push("/")

    }catch(e:any){
      setError(e.message);
      console.log(e)
    }finally{
      setLoading(false);
    }
  }
  return (
    <div className="flex items-center justify-center h-screen bg-gray-100 dark:bg-gray-900">
      <div className="w-full max-w-md p-6 bg-white rounded-lg shadow-md dark:bg-gray-800">
        <h1 className="text-2xl font-bold mb-6 dark:text-gray-200">New Post</h1>
        {loading && <p className="text-blue-600">Creating post...</p>}
        <form className="space-y-4">
          <div>
            <label className="block mb-1 text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="title">
              Title
            </label>
            <input onChange={(e)=>setTitle(e.target.value)}
              className="w-full px-3 py-2 border border-gray-200 border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:text-gray-200 dark:border-gray-600 dark:border-gray-800"
              id="title"
              placeholder="Enter post title"
              type="text"
            />
          </div>
          <div>
            <label className="block mb-1 text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="content">
              Content
            </label>
            <textarea onChange={(e)=>setContent(e.target.value)}
              className="w-full px-3 py-2 border border-gray-200 border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:text-gray-200 dark:border-gray-600 dark:border-gray-800"
              id="content"
              placeholder="Enter post content"
              rows={3}
            />
          </div>
          <div>
            <label className="block mb-1 text-sm font-medium text-gray-700 dark:text-gray-300" htmlFor="image">
              Image URL
            </label>
            <input onChange={(e)=>setImage(e.target.value)}
              className="w-full px-3 py-2 border border-gray-200 border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 dark:bg-gray-700 dark:text-gray-200 dark:border-gray-600 dark:border-gray-800"
              id="image"
              placeholder="Enter image URL"
              type="text"
            />
          </div>
          <button onClick={handlePost}
            className="w-full px-4 py-2 font-medium text-white bg-indigo-600 rounded-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 dark:bg-indigo-500 dark:hover:bg-indigo-600"
            type="submit"
          >
            Create Post
          </button>
        </form>
        {error && <p className="mt-4 text-red-500">{error}</p>}
      </div>
    </div>
  )
}
