"use client"

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6rWHEAoEhK2
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "../ui/button"
import { signOut, useSession } from "next-auth/react"
import { CircleX, Menu } from "lucide-react"
import { useState } from "react"

export function Navbar() {

  const session = useSession();
  const [menu,setMenu] = useState(false);
  return (
    <header className="flex h-16 items-center justify-between px-4 md:px-6">
      <Link className="flex items-center gap-2 " href="/">
        <MountainIcon className="h-6 w-6" />
        <span className="text-lg font-bold">Blog</span>
      </Link>
      <form className="flex-1 max-w-md">
        <div className="relative max-lg:ml-2 flex gap-3 ">
          <SearchIcon className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-gray-500 dark:text-gray-400" />
          <Input
            className="w-full max-lg:w-[13rem] rounded-md border border-gray-200 bg-white px-8 py-2 text-sm shadow-sm transition-colors focus:border-gray-900 focus:outline-none focus:ring-1 focus:ring-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:text-gray-50 dark:focus:border-gray-300 dark:focus:ring-gray-300 dark:border-gray-800"
            placeholder="Search articles..."
            type="search"
          />
          <div className="items-center justify-center flex lg:hidden">
            <Menu className="click:ease-in-out duration-200 hover:scale-110 duration-200" onClick={()=>setMenu(!menu)}/>
            {menu && (
    <div className="fixed inset-0 flex items-center justify-center z-50 bg-black h-screen w-screen">
      <div className="text-white  absolute top-0 right-0 mr-4 mt-4">
      <CircleX onClick={()=>setMenu(!menu)} className="hover:scale-110 duration-200 ease-out" />
      </div>

      <div className="text-white  rounded-lg p-8 ">
        <nav className="flex flex-col gap-4">
        <Button onClick={()=>signOut()} className="text-center hover:scale-110 duration-200 text-xl font-bold font-sans">
            {session?.status === "authenticated" ? 'Logout' : (
              <Link href="/login" >Login</Link>
            )}
          </Button>
          <Link
            href="/create"
            className="text-center hover:scale-110 duration-150 text-xl font-sans font-bold "
          >
            Create Post
          </Link>
          <Link
            href="/about"
            className="text-center hover:scale-110 duration-150 text-xl font-bold font-sans"
          >
            About
          </Link>

        </nav>
      </div>
    </div>
  )}
          </div>
        </div>
      </form>
      <nav className="hidden gap-4 md:flex items-center">
      <Button onClick={()=>signOut()} className="text-sm bg-black rounded-md p-2 text-white font-medium hover:underline underline-offset-4">
          {session?.status === "authenticated" ? "Logout" : (
            <Link href="/login">Login</Link>
          )}
        </Button>
        <Link className="text-sm bg-black rounded-md p-2 text-white font-medium hover:underline underline-offset-4" href="/create">
          Create Post
        </Link>
        <Link className="text-sm font-medium hover:underline underline-offset-4" href="/about">
          About
        </Link>
      </nav>
    </header>
  )
}

function MountainIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function SearchIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}
